### ISSUE TITLE
Keycap colors on imgur gallery?

### ISSUE THREAD

**Issue by drudru** [jasonm23/1971-wasd#4]
Hi,

I just checked out your imgur gallery: https://imgur.com/a/IVlZk

Is that really the WASD version of 'mint' for the keycap color on the left side of the keyboard?
If so, it looks great.

Also, in some of the pics on imgur you have non-brown keycaps.
Which color did you go with from the WASD site?

https://www.wasdkeyboards.com/designer-text-color

**Comment by jasonm23** [comment]
Hi Dru, WASD say it best ...

> Due to the nature of print color reproduction; hex value color representation on-screen may vary from finished product and can only be used as an approximation.

This does apply to photos depending on lighting etc.

**Comment by jasonm23** [comment]
Since I gave this set to one of my team mates back then, I can't look at the set now.

But I remember we all thought it was nice.

**Comment by jasonm23** [comment]
That top photo is filtered - the rest are unfiltered. BTW

**Comment by drudru** [comment]
Thanks for the info on the first pic, that is helpful.
Just comparing the 2nd and 3rd tells me that these are two different sets.

**Comment by jasonm23** [comment]
Only one set ever made.

**Comment by drudru** [comment]
Here are two pictures in that gallery. You are saying these are the same set?

![1971-1](https://user-images.githubusercontent.com/546/90990172-dddd9c80-e564-11ea-9b57-a9ef199162f5.jpg)

![1971-2](https://user-images.githubusercontent.com/546/90990182-eb932200-e564-11ea-9845-da909376eb9d.jpg)

**Comment by jasonm23** [comment]
One set of each color way.  (Grey, Brown)

**Comment by drudru** [comment]
Ok 👍
